### ISSUE TITLE
SSL errors on EL5

### ISSUE THREAD

**Issue by Gillingham** [iuscommunity-pkg/python27-virtualenv#1]
Since virtualenv bundles it's own pip, it's affected by the same issue as iuscommunity-pkg/python27-pip#1

Upstream bug(s) pypa/pip#2395 and pypa/virtualenv#718

**Comment by cgtx** [comment]
A temporary workaround until we get the proper fix from upstream is to use the `--trusted-host` flag.

```
pip --trusted-host pypi.python.org install foobar
```

**Comment by cgtx** [comment]
This is fixed in urllib3 1.10.1.  Now we just have to wait for the requests to bundle that, and then pip to bundle that, and then virtualenv to bundle that.

**Comment by cgtx** [comment]
Verfied fixed in python27-virtualenv-12.1.1-1.ius, which is currently in the testing repos.
